添加联系人的请求是用ajax触发后台更新数据库的
更新联系人功能正常，保存后自动返回
但新建联系人，在后台调用save后返回响应，前台无法正确接收到响应，后端报错
找了许久，改了许久，不知道问题在哪，stackoverflow上也有类似问题，目前猜测为django的BUG。